# Generated by Django 6.0.7 on 2026-07-17 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name, e.g. Boxes', max_length=64)),
                ('color', models.CharField(blank=True, default='#F25C05', max_length=16)),
                ('route_path', models.CharField(help_text='Frontend path, e.g. /inventory', max_length=128)),
                ('category', models.CharField(choices=[('workspace', 'Workspace'), ('consumer', 'Consumer'), ('admin', 'Admin'), ('system', 'System')], db_index=True, default='workspace', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='orguser',
            name='role_kind',
            field=models.CharField(choices=[('none', 'None'), ('admin', 'Admin'), ('staff', 'Staff')], db_index=True, default='none', help_text='None → consumer portal; Admin → org admin dashboard; Staff → module permissions', max_length=16),
        ),
        migrations.AddField(
            model_name='role',
            name='kind',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], db_index=True, default='staff', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('admin', 'Admin'), ('staff', 'Staff')], db_index=True, default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='organization',
            name='account_type',
            field=models.CharField(choices=[('producer', 'Producer'), ('manufacture', 'Manufacture'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('wholeseller_sole', 'Wholeseller (Sole)'), ('retailer', 'Retailer'), ('software', 'Software'), ('construction', 'Construction'), ('marketing', 'Marketing'), ('services', 'Services'), ('custom', 'Custom')], db_index=True, default='custom', max_length=32),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('producer', 'Producer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('consumer_org', 'Consumer Organization'), ('supplier', 'Supplier'), ('software', 'Software'), ('construction', 'Construction'), ('marketing', 'Marketing'), ('services', 'Services'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_users', to='core.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions_json',
            field=models.JSONField(blank=True, default=dict, help_text='Module access map, e.g. {"inventory": "F", "finance": "R"} or {"*": true}'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('producer', 'Producer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('consumer', 'Consumer')], db_index=True, default='consumer', max_length=32),
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('F', 'Full'), ('R', 'Read'), ('N', 'None')], default='F', max_length=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='core.role')),
            ],
            options={
                'verbose_name': 'role module permission',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='roles', through='core.RoleModulePermission', to='core.module'),
        ),
    ]
