# Generated by Django 6.0.7 on 2026-07-18 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portal_modules_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipRoleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('tier', models.CharField(choices=[('top', 'CEO / MD'), ('executive', 'Executive Team'), ('hr', 'HR Department')], db_index=True, max_length=16)),
                ('reports_to_code', models.CharField(blank=True, help_text='Code of the parent leadership role (empty for top).', max_length=64)),
                ('department_code', models.CharField(blank=True, max_length=32)),
                ('department_name', models.CharField(blank=True, max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='positionmaster',
            options={'ordering': ['sort_order', 'designation']},
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Default-account applicant (HR Form Applicant).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='organizations/registration_certificates/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_mode',
            field=models.CharField(blank=True, choices=[('already_registered', 'Already Registered Company'), ('new_company', 'New Company')], db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='share_allocation_document',
            field=models.FileField(blank=True, null=True, upload_to='organizations/share_allocation/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_capital',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Authorized / total capital in NPR.', max_digits=18),
        ),
        migrations.AddField(
            model_name='positionmaster',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='positionmaster',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positionmaster',
            name='leadership_tier',
            field=models.CharField(choices=[('none', 'None'), ('top', 'CEO / MD'), ('executive', 'Executive Team'), ('hr', 'HR Department')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='positionmaster',
            name='sort_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('word', 'Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('blog', 'Blog'), ('news', 'News'), ('mou', 'MOU'), ('agreement', 'Agreement'), ('minute', 'Minute'), ('niyamawali', 'Niyamawali (Company Regulations)'), ('prabandhapatra', 'Prabandhapatra (Memorandum/Articles)'), ('company_registration', 'Company Registration Certificate'), ('share_allocation', 'Share Allocation'), ('custom', 'Custom')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='doc_type',
            field=models.CharField(choices=[('mou', 'MOU'), ('agreement', 'Agreement'), ('minute', 'Minute'), ('niyamawali', 'Niyamawali (Company Regulations)'), ('prabandhapatra', 'Prabandhapatra (Memorandum/Articles)'), ('custom', 'Custom')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='current_stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='applied', max_length=16),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vat_pan_no',
            field=models.CharField(blank=True, db_index=True, help_text='Required for already-registered companies.', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('producer', 'Producer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('default', 'Default'), ('consumer', 'Consumer')], db_index=True, default='consumer', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplicant',
            unique_together={('vacancy', 'user')},
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('registration_certificate', 'Company Registration Certificate'), ('share_allocation', 'Share Allocation'), ('pan', 'PAN Document'), ('other', 'Other')], db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='organizations/company_documents/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='core.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_company_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('share_units', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('is_default', models.BooleanField(default=False, help_text='Mark as the primary / default shareholder for the company.')),
                ('citizenship_document', models.FileField(blank=True, null=True, upload_to='organizations/shareholders/citizenship/')),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shareholdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-percentage', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLeadershipSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_override', models.CharField(blank=True, max_length=128)),
                ('is_filled', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership_seats', to='core.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_seats', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership_seats', to=settings.AUTH_USER_MODEL)),
                ('role_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='core.leadershiproledefinition')),
            ],
            options={
                'ordering': ['role_definition__sort_order'],
                'unique_together': {('organization', 'role_definition')},
            },
        ),
    ]
