# Generated by Django 6.0.7 on 2026-07-25 10:28

import core.models.base
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enterprise_erp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic', core.models.base.CurrencyField(decimal_places=2, default=0, max_digits=18)),
                ('da', core.models.base.CurrencyField(decimal_places=2, default=0, help_text='Dearness allowance', max_digits=18)),
                ('grade_allowance', core.models.base.CurrencyField(decimal_places=2, default=0, max_digits=18)),
                ('shift_allowance', core.models.base.CurrencyField(decimal_places=2, default=0, max_digits=18)),
                ('meal_allowance', core.models.base.CurrencyField(decimal_places=2, default=0, max_digits=18)),
                ('transport_allowance', core.models.base.CurrencyField(decimal_places=2, default=0, max_digits=18)),
                ('other_allowances', core.models.base.CurrencyField(decimal_places=2, default=0, max_digits=18)),
                ('deductions', core.models.base.CurrencyField(decimal_places=2, default=0, help_text='Fixed monthly deductions (SSF, CIT, etc.)', max_digits=18)),
                ('ot_rate_per_hour', core.models.base.CurrencyField(decimal_places=2, default=0, help_text='Overtime rate used in payroll', max_digits=18)),
                ('currency_code', models.CharField(default='NPR', max_length=8)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='core.employee')),
            ],
            options={
                'verbose_name_plural': 'employee salaries',
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('task_name', models.CharField(max_length=255)),
                ('supervisor_role', models.CharField(blank=True, max_length=128)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = global default template shared across orgs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_task_templates', to='core.organization')),
            ],
            options={
                'ordering': ['sort_order', 'day_number', 'task_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('pass_score', models.PositiveSmallIntegerField(default=80)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = global catalog entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='core.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
