/** Account-type module presets for Super Admin roles UI (display catalog). */

export const MODULES_BY_ACCOUNT_TYPE: Record<string, readonly string[]> = {
  super_admin: [
    "dashboard",
    "tasks",
    "hr",
    "production",
    "inventory",
    "sales",
    "finance",
    "procurement",
    "quality",
    "crm",
    "maintenance",
    "logistics",
    "stores",
    "rnd",
    "it",
    "process",
    "governance",
    "docs",
    "admin",
    "audit",
    "copilot",
    "feed",
    "commerce",
    "media",
    "payments",
    "chat",
    "customer",
    "jobs",
  ],
  producer: [
    "dashboard",
    "tasks",
    "hr",
    "production",
    "inventory",
    "sales",
    "finance",
    "procurement",
    "quality",
    "crm",
    "maintenance",
    "logistics",
    "stores",
    "process",
    "rnd",
    "admin",
    "governance",
    "audit",
    "chat",
  ],
  distributor: [
    "dashboard",
    "tasks",
    "hr",
    "inventory",
    "sales",
    "finance",
    "procurement",
    "crm",
    "logistics",
    "stores",
    "admin",
    "audit",
    "chat",
  ],
  wholesaler: [
    "dashboard",
    "tasks",
    "hr",
    "inventory",
    "sales",
    "finance",
    "procurement",
    "crm",
    "stores",
    "admin",
    "audit",
    "chat",
  ],
  retailer: [
    "dashboard",
    "tasks",
    "hr",
    "inventory",
    "sales",
    "finance",
    "procurement",
    "crm",
    "stores",
    "admin",
    "commerce",
    "chat",
  ],
  consumer: ["customer", "feed", "commerce", "media", "payments", "chat", "jobs"],
};

export function normalizeAccountType(accountType?: string | null): string {
  if (!accountType) return "consumer";
  const key = accountType.toLowerCase();
  if (key === "manufacture") return "producer";
  if (key === "wholeseller_sole") return "wholesaler";
  return key;
}
