import os
"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i1opg4j^t(ko$3-ss0wsnes9^nr8)k&el5s&4q4uc&c-lvc0)&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.SessionTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}
CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'core.User'

# ------------------------------------------------------------------
# Jazzmin — advanced admin UI
# ------------------------------------------------------------------
JAZZMIN_SETTINGS = {
    'site_title': 'Sunyazon BEOS',
    'site_header': 'Sunyazon',
    'site_brand': 'Sunyazon BEOS',
    'welcome_sign': 'Welcome to Sunyazon — Business Ecosystem Operating System',
    'copyright': 'Sunyzon Company Pvt. Ltd.',
    'search_model': ['core.User', 'core.Product', 'core.Order', 'core.Organization'],
    'topmenu_links': [
        {'name': 'Dashboard', 'url': 'admin:index', 'permissions': ['auth.view_user']},
        {'model': 'core.User'},
        {'model': 'core.Organization'},
        {'model': 'core.Product'},
        {'model': 'core.Order'},
    ],
    'usermenu_links': [
        {'model': 'core.user'},
    ],
    'show_sidebar': True,
    'navigation_expanded': False,
    'order_with_respect_to': [
        'core.User', 'core.UserProfile', 'core.KYCDocument',
        'core.Organization', 'core.Employee',
        'core.Product', 'core.Order',
        'core.WorkOrder', 'core.ProcessDefinition',
    ],
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.Group': 'fas fa-users',
        'core.User': 'fas fa-user',
        'core.UserProfile': 'fas fa-id-card',
        'core.KYCDocument': 'fas fa-passport',
        'core.Address': 'fas fa-map-marker-alt',
        'core.Session': 'fas fa-key',
        'core.Country': 'fas fa-globe',
        'core.Province': 'fas fa-map',
        'core.District': 'fas fa-map-marked',
        'core.Municipality': 'fas fa-city',
        'core.Tenant': 'fas fa-building',
        'core.Actor': 'fas fa-user-astronaut',
        'core.Task': 'fas fa-tasks',
        'core.Approval': 'fas fa-check-double',
        'core.AuditLog': 'fas fa-history',
        'core.Notification': 'fas fa-bell',
        'core.Organization': 'fas fa-industry',
        'core.Module': 'fas fa-th-large',
        'core.RoleModulePermission': 'fas fa-key',
        'core.OrgUser': 'fas fa-user-tie',
        'core.Department': 'fas fa-sitemap',
        'core.Branch': 'fas fa-code-branch',
        'core.Team': 'fas fa-people-group',
        'core.Meeting': 'fas fa-handshake',
        'core.PlatformChannel': 'fas fa-tv',
        'core.FeedPost': 'fas fa-rss',
        'core.Story': 'fas fa-circle-notch',
        'core.Friendship': 'fas fa-user-friends',
        'core.MediaAsset': 'fas fa-photo-video',
        'core.LiveStream': 'fas fa-broadcast-tower',
        'core.Category': 'fas fa-folder-tree',
        'core.Product': 'fas fa-box-open',
        'core.Cart': 'fas fa-shopping-cart',
        'core.Order': 'fas fa-file-invoice-dollar',
        'core.Review': 'fas fa-star',
        'core.PaymentGateway': 'fas fa-credit-card',
        'core.PaymentTransaction': 'fas fa-money-check-alt',
        'core.AdPlan': 'fas fa-bullhorn',
        'core.AdCampaign': 'fas fa-ad',
        'core.Document': 'fas fa-file-alt',
        'core.BlogPost': 'fas fa-blog',
        'core.ChatThread': 'fas fa-comments',
        'core.ChatMessage': 'fas fa-comment-dots',
        'core.CallSession': 'fas fa-phone',
        'core.HelpTicket': 'fas fa-life-ring',
        'core.Employee': 'fas fa-id-badge',
        'core.JobVacancy': 'fas fa-briefcase',
        'core.Attendance': 'fas fa-calendar-check',
        'core.LeaveRequest': 'fas fa-umbrella-beach',
        'core.PayrollRun': 'fas fa-money-bill-wave',
        'core.ChartOfAccount': 'fas fa-list-ol',
        'core.JournalVoucher': 'fas fa-book',
        'core.Purchase': 'fas fa-cart-arrow-down',
        'core.PurchaseOrder': 'fas fa-file-signature',
        'core.Sales': 'fas fa-cash-register',
        'core.SalesOrder': 'fas fa-file-invoice',
        'core.Ledger': 'fas fa-book-open',
        'core.Vendor': 'fas fa-truck-loading',
        'core.Warehouse': 'fas fa-warehouse',
        'core.ItemMaster': 'fas fa-cubes',
        'core.StockLedger': 'fas fa-boxes',
        'core.GRN': 'fas fa-dolly',
        'core.IndustryTemplate': 'fas fa-layer-group',
        'core.ProcessDefinition': 'fas fa-project-diagram',
        'core.WorkOrder': 'fas fa-clipboard-list',
        'core.ProcessRun': 'fas fa-play-circle',
        'core.Batch': 'fas fa-barcode',
        'core.BOM': 'fas fa-list-alt',
        'core.Party': 'fas fa-store',
        'core.Dispatch': 'fas fa-shipping-fast',
        'core.Vehicle': 'fas fa-truck',
        'core.NCR': 'fas fa-exclamation-triangle',
        'core.CAPA': 'fas fa-tools',
        'core.Complaint': 'fas fa-angry',
        'core.PipelineDeal': 'fas fa-funnel-dollar',
        'core.Equipment': 'fas fa-cogs',
        'core.KPISnapshot': 'fas fa-chart-line',
        'core.DashboardWidget': 'fas fa-th-large',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': True,
    'custom_css': None,
    'custom_js': None,
    'show_ui_builder': False,
    'changeform_format': 'horizontal_tabs',
    'changeform_format_overrides': {
        'core.user': 'collapsible',
        'core.order': 'horizontal_tabs',
        'core.product': 'horizontal_tabs',
        'core.organization': 'horizontal_tabs',
        'core.workorder': 'horizontal_tabs',
    },
    'language_chooser': False,
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-dark',
    'accent': 'accent-teal',
    'navbar': 'navbar-dark navbar-primary',
    'no_navbar_border': False,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': True,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'flatly',
    'dark_mode_theme': 'darkly',
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
    'actions_sticky_top': True,
}

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
