from django.urls import path, include

from core.views_auth import (
    LoginView,
    LogoutView,
    MeView,
    ModuleCatalogView,
    ModuleListView,
    PortalView,
    RegisterView,
)
from core.views_customer import (
    CustomerAddressDetailView,
    CustomerAddressesView,
    CustomerNearestShopsView,
    CustomerOptionsView,
    CustomerOrderDetailView,
    CustomerOrdersView,
    CustomerOverviewView,
)
from core.views_company import (
    CompanyLookupView,
    CompanyRegistrationOptionsView,
    CompanyRegistrationView,
    GovernanceDocumentDetailView,
    GovernanceDocumentPrintView,
    GovernanceDocumentsView,
    JobApplicationReviewView,
    JobApplicationsView,
    JobVacanciesView,
    JobVacancyDetailView,
    LeadershipView,
    ShareholdersView,
)
from core.views_docs import (
    DocsDocumentDetailView,
    DocsDocumentsView,
    DocsOptionsView,
    DocsOverviewView,
    DocsTemplateDetailView,
    DocsTemplatesView,
)
from core.views_hr import (
    HRAttendanceDetailView,
    HRAttendanceView,
    HRDepartmentsView,
    HREmployeeDetailView,
    HREmployeeSalaryView,
    HREmployeesView,
    HRLeaveDetailView,
    HRLeaveView,
    HROnboardingDetailView,
    HROnboardingTaskDetailView,
    HROnboardingTasksView,
    HROnboardingTemplateDetailView,
    HROnboardingTemplatesView,
    HROnboardingView,
    HROptionsView,
    HROverviewView,
    HRPayrollDetailView,
    HRPayrollView,
    HRPositionDetailView,
    HRPositionsView,
    HRScoringDetailView,
    HRScoringView,
    HRTrainingDetailView,
    HRTrainingModuleDetailView,
    HRTrainingModulesView,
    HRTrainingView,
)
from core.views_maintenance import (
    MaintenanceCalibrationDetailView,
    MaintenanceCalibrationsView,
    MaintenanceEquipmentDetailView,
    MaintenanceEquipmentView,
    MaintenanceOptionsView,
    MaintenanceOverviewView,
    MaintenancePMScheduleDetailView,
    MaintenancePMSchedulesView,
    MaintenanceWorkOrderDetailView,
    MaintenanceWorkOrdersView,
)
from core.views_quality import (
    QualityCAPADetailView,
    QualityCAPAView,
    QualityIPQCDetailView,
    QualityIPQCView,
    QualityIncomingDetailView,
    QualityIncomingView,
    QualityLabDetailView,
    QualityLabView,
    QualityMasterDetailView,
    QualityMasterView,
    QualityNCRDetailView,
    QualityNCRView,
    QualityOptionsView,
    QualityOverviewView,
    QualityReleaseDetailView,
    QualityReleaseView,
)
from core.views_commerce import (
    CommerceCategoriesView,
    CommerceCategoryDetailView,
    CommerceOptionsView,
    CommerceOrderDetailView,
    CommerceOrdersView,
    CommerceOverviewView,
    CommerceProductDetailView,
    CommerceProductsView,
)
from core.views_production import (
    ProductionBOMDetailView,
    ProductionBOMLineView,
    ProductionBOMsView,
    ProductionBatchDetailView,
    ProductionBatchesView,
    ProductionCostingDetailView,
    ProductionCostingView,
    ProductionDamageDetailView,
    ProductionDamageView,
    ProductionOptionsView,
    ProductionOverviewView,
    ProductionRegisterView,
    ProductionWIPDetailView,
    ProductionWIPView,
    ProductionWorkOrderDetailView,
    ProductionWorkOrdersView,
    ProductionWorkingReportDetailView,
    ProductionWorkingReportsView,
)
from core.views_rnd import (
    RndOptionsView,
    RndOverviewView,
)
from core.views_inventory import (
    InventoryAdjustmentDetailView,
    InventoryAdjustmentsView,
    InventoryGRNDetailView,
    InventoryGRNsView,
    InventoryItemDetailView,
    InventoryItemsView,
    InventoryLedgerView,
    InventoryMaterialIssueDetailView,
    InventoryMaterialIssuesView,
    InventoryOptionsView,
    InventoryOverviewView,
    InventoryReorderPRView,
    InventoryStockView,
    InventoryWarehouseDetailView,
    InventoryWarehousesView,
)
from core.views_logistics import (
    LogisticsDispatchDetailView,
    LogisticsDispatchesView,
    LogisticsOptionsView,
    LogisticsOverviewView,
    LogisticsPodDetailView,
    LogisticsPodsView,
    LogisticsRouteDetailView,
    LogisticsRoutesView,
    LogisticsVehicleDetailView,
    LogisticsVehiclesView,
)
from core.views_sales import (
    SalesASMOrderDetailView,
    SalesASMOrdersView,
    SalesDealerOrderDetailView,
    SalesDealerOrdersView,
    SalesOptionsView,
    SalesOverviewView,
    SalesPartiesView,
    SalesPartyDetailView,
    SalesRetailOrderDetailView,
    SalesRetailOrdersView,
    SalesReturnDetailView,
    SalesReturnsView,
    SalesSchemeDetailView,
    SalesSchemesView,
    SalesTerritoriesView,
    SalesTerritoryDetailView,
)
from core.views_it import (
    ItOptionsView,
    ItOverviewView,
    ItSessionsView,
    ItTicketDetailView,
    ItTicketsView,
)
from core.views_finance import (
    FinanceCashBankDetailView,
    FinanceCashBanksView,
    FinanceChequeDetailView,
    FinanceChequesView,
    FinanceCOADetailView,
    FinanceCOAView,
    FinanceCreditNoteDetailView,
    FinanceCreditNotesView,
    FinanceDayBookView,
    FinanceDebitNoteDetailView,
    FinanceDebitNotesView,
    FinanceIncomeExpenseDetailView,
    FinanceIncomeExpensesView,
    FinanceLedgerView,
    FinanceOptionsView,
    FinanceOverviewView,
    FinancePaymentsView,
    FinancePnLView,
    FinancePurchaseDetailView,
    FinancePurchaseOrderDetailView,
    FinancePurchaseOrdersView,
    FinancePurchasesView,
    FinanceReceiptsView,
    FinanceSalesDetailView,
    FinanceSalesOrderDetailView,
    FinanceSalesOrdersView,
    FinanceSalesView,
    FinanceTaxDetailView,
    FinanceTaxView,
    FinanceVoucherDetailView,
    FinanceVouchersView,
)
from core.views_crm import (
    CrmActivitiesView,
    CrmActivityDetailView,
    CrmComplaintDetailView,
    CrmComplaintsView,
    CrmDealDetailView,
    CrmDealsView,
    CrmOptionsView,
    CrmOverviewView,
)
from core.views_domain import (
    AdminView,
    AttendanceView,
    AuditView,
    AuthKycView,
    ChatView,
    CommerceView,
    CrmView,
    CustomerView,
    DashboardView,
    DocsView,
    EmployeesView,
    FeedView,
    FinanceView,
    GovernanceView,
    ItView,
    LogisticsView,
    MaintenanceView,
    MediaView,
    NotificationsView,
    PaymentsView,
    ProcurementView,
    QualityView,
    RndView,
    SalesByRegionView,
    SalesOrdersView,
    StockMovementsView,
    StockView,
    TasksView,
    WorkOrdersView,
)
from core.views_procurement import (
    ProcurementGRNDetailView,
    ProcurementGRNsView,
    ProcurementOptionsView,
    ProcurementOrderDetailView,
    ProcurementOrdersView,
    ProcurementOverviewView,
    ProcurementRFQDetailView,
    ProcurementRFQsView,
    ProcurementRequisitionDetailView,
    ProcurementRequisitionsView,
    ProcurementVendorDetailView,
    ProcurementVendorsView,
)
from core.views_media import (
    MediaAssetDetailView,
    MediaAssetsView,
    MediaLiveStreamDetailView,
    MediaLiveStreamsView,
    MediaOptionsView,
    MediaOverviewView,
    MediaPlaylistDetailView,
    MediaPlaylistsView,
)
from core.views_domain_fbv import (
    auth_kyc_verify,
    chat_messages,
    crm_deal_action,
    feed_engage,
    feed_publish,
    finance_payment_action,
    finance_voucher_action,
    logistics_dispatch_action,
    maintenance_pm_generate,
    maintenance_wo_action,
    material_issue_action,
    notification_mark_read,
    process_action,
    process_dashboard,
    process_run_stage_action,
    quality_capa_close,
    quality_incoming_action,
    quality_ncr_create,
    quality_qc_action,
    quality_release_action,
    sales_order_action,
    stock_adjustment_approve,
    stock_ledger_post,
    stock_reorder_pr,
    work_order_action,
)
from core.views_payments import (
    PaymentsCampaignDetailView,
    PaymentsCampaignsView,
    PaymentsGatewaysView,
    PaymentsOptionsView,
    PaymentsOverviewView,
    PaymentsTransactionDetailView,
    PaymentsTransactionsView,
)

urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/portal/", PortalView.as_view(), name="auth-portal"),
    path("auth/modules/", ModuleListView.as_view(), name="auth-modules"),
    path("modules/", ModuleCatalogView.as_view(), name="module-catalog"),
    # Enterprise CRUD (dynamic ERP)
    path("", include("core.api.urls")),
    # Company registration
    path(
        "company/registration/options/",
        CompanyRegistrationOptionsView.as_view(),
        name="company-registration-options",
    ),
    path(
        "company/registration/",
        CompanyRegistrationView.as_view(),
        name="company-registration",
    ),
    path("company/lookup/", CompanyLookupView.as_view(), name="company-lookup"),
    path("company/shareholders/", ShareholdersView.as_view(), name="company-shareholders"),
    path("company/leadership/", LeadershipView.as_view(), name="company-leadership"),
    # Governance documents (Niyamawali / Prabandhapatra)
    path(
        "governance/documents/",
        GovernanceDocumentsView.as_view(),
        name="governance-documents",
    ),
    path(
        "governance/documents/<uuid:doc_id>/",
        GovernanceDocumentDetailView.as_view(),
        name="governance-document-detail",
    ),
    path(
        "governance/documents/<uuid:doc_id>/print/",
        GovernanceDocumentPrintView.as_view(),
        name="governance-document-print",
    ),
    # HR module (model-backed CRUD)
    path("hr/overview/", HROverviewView.as_view(), name="hr-overview"),
    path("hr/options/", HROptionsView.as_view(), name="hr-options"),
    path("hr/positions/", HRPositionsView.as_view(), name="hr-positions"),
    path(
        "hr/positions/<uuid:position_id>/",
        HRPositionDetailView.as_view(),
        name="hr-position-detail",
    ),
    path("hr/employees/", HREmployeesView.as_view(), name="hr-employees"),
    path(
        "hr/employees/<uuid:employee_id>/",
        HREmployeeDetailView.as_view(),
        name="hr-employee-detail",
    ),
    path(
        "hr/employees/<uuid:employee_id>/salary/",
        HREmployeeSalaryView.as_view(),
        name="hr-employee-salary",
    ),
    path("hr/departments/", HRDepartmentsView.as_view(), name="hr-departments"),
    path("hr/onboarding/", HROnboardingView.as_view(), name="hr-onboarding"),
    path(
        "hr/onboarding/<uuid:process_id>/",
        HROnboardingDetailView.as_view(),
        name="hr-onboarding-detail",
    ),
    path("hr/onboarding-tasks/", HROnboardingTasksView.as_view(), name="hr-onboarding-tasks"),
    path(
        "hr/onboarding-tasks/<uuid:task_id>/",
        HROnboardingTaskDetailView.as_view(),
        name="hr-onboarding-task-detail",
    ),
    path(
        "hr/onboarding-templates/",
        HROnboardingTemplatesView.as_view(),
        name="hr-onboarding-templates",
    ),
    path(
        "hr/onboarding-templates/<uuid:template_id>/",
        HROnboardingTemplateDetailView.as_view(),
        name="hr-onboarding-template-detail",
    ),
    path("hr/training/", HRTrainingView.as_view(), name="hr-training"),
    path(
        "hr/training/<uuid:training_id>/",
        HRTrainingDetailView.as_view(),
        name="hr-training-detail",
    ),
    path("hr/training-modules/", HRTrainingModulesView.as_view(), name="hr-training-modules"),
    path(
        "hr/training-modules/<uuid:module_id>/",
        HRTrainingModuleDetailView.as_view(),
        name="hr-training-module-detail",
    ),
    path("hr/attendance/", HRAttendanceView.as_view(), name="hr-attendance"),
    path(
        "hr/attendance/<uuid:attendance_id>/",
        HRAttendanceDetailView.as_view(),
        name="hr-attendance-detail",
    ),
    path("hr/leave/", HRLeaveView.as_view(), name="hr-leave"),
    path(
        "hr/leave/<uuid:leave_id>/",
        HRLeaveDetailView.as_view(),
        name="hr-leave-detail",
    ),
    path("hr/payroll/", HRPayrollView.as_view(), name="hr-payroll"),
    path(
        "hr/payroll/<uuid:payroll_id>/",
        HRPayrollDetailView.as_view(),
        name="hr-payroll-detail",
    ),
    path("hr/scoring/", HRScoringView.as_view(), name="hr-scoring"),
    path(
        "hr/scoring/<uuid:scoring_id>/",
        HRScoringDetailView.as_view(),
        name="hr-scoring-detail",
    ),
    # HR recruitment
    path("hr/vacancies/", JobVacanciesView.as_view(), name="hr-vacancies"),
    path(
        "hr/vacancies/<uuid:vacancy_id>/",
        JobVacancyDetailView.as_view(),
        name="hr-vacancy-detail",
    ),
    path("hr/applications/", JobApplicationsView.as_view(), name="hr-applications"),
    path(
        "hr/applications/<uuid:applicant_id>/review/",
        JobApplicationReviewView.as_view(),
        name="hr-application-review",
    ),
    # Domain APIs (GET dashboards + function-based mutation actions)
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("tasks/", TasksView.as_view(), name="tasks"),
    path("employees/", EmployeesView.as_view(), name="employees"),
    path("attendance/", AttendanceView.as_view(), name="attendance"),
    path("work-orders/", WorkOrdersView.as_view(), name="work-orders"),
    path("work-orders/<uuid:wo_id>/", work_order_action, name="work-order-action"),
    path("production/overview/", ProductionOverviewView.as_view(), name="production-overview"),
    path("production/options/", ProductionOptionsView.as_view(), name="production-options"),
    path("production/boms/", ProductionBOMsView.as_view(), name="production-boms"),
    path("production/boms/<uuid:bom_id>/", ProductionBOMDetailView.as_view(), name="production-bom-detail"),
    path("production/boms/<uuid:bom_id>/lines/", ProductionBOMLineView.as_view(), name="production-bom-lines"),
    path(
        "production/boms/<uuid:bom_id>/lines/<uuid:line_id>/",
        ProductionBOMLineView.as_view(),
        name="production-bom-line-detail",
    ),
    path("production/batches/", ProductionBatchesView.as_view(), name="production-batches"),
    path(
        "production/batches/<uuid:batch_id>/",
        ProductionBatchDetailView.as_view(),
        name="production-batch-detail",
    ),
    path("production/work-orders/", ProductionWorkOrdersView.as_view(), name="production-work-orders"),
    path(
        "production/work-orders/<uuid:wo_id>/",
        ProductionWorkOrderDetailView.as_view(),
        name="production-work-order-detail",
    ),
    path("production/wip/", ProductionWIPView.as_view(), name="production-wip"),
    path("production/wip/<uuid:wip_id>/", ProductionWIPDetailView.as_view(), name="production-wip-detail"),
    path("production/costing/", ProductionCostingView.as_view(), name="production-costing"),
    path(
        "production/costing/<uuid:costing_id>/",
        ProductionCostingDetailView.as_view(),
        name="production-costing-detail",
    ),
    path("production/damage/", ProductionDamageView.as_view(), name="production-damage"),
    path(
        "production/damage/<uuid:damage_id>/",
        ProductionDamageDetailView.as_view(),
        name="production-damage-detail",
    ),
    path(
        "production/working-reports/",
        ProductionWorkingReportsView.as_view(),
        name="production-working-reports",
    ),
    path(
        "production/working-reports/<uuid:report_id>/",
        ProductionWorkingReportDetailView.as_view(),
        name="production-working-report-detail",
    ),
    path("production/register/", ProductionRegisterView.as_view(), name="production-register"),
    # Inventory module (model-backed CRUD)
    path("inventory/overview/", InventoryOverviewView.as_view(), name="inventory-overview"),
    path("inventory/options/", InventoryOptionsView.as_view(), name="inventory-options"),
    path("inventory/warehouses/", InventoryWarehousesView.as_view(), name="inventory-warehouses"),
    path(
        "inventory/warehouses/<uuid:warehouse_id>/",
        InventoryWarehouseDetailView.as_view(),
        name="inventory-warehouse-detail",
    ),
    path("inventory/items/", InventoryItemsView.as_view(), name="inventory-items"),
    path(
        "inventory/items/<uuid:item_id>/",
        InventoryItemDetailView.as_view(),
        name="inventory-item-detail",
    ),
    path("inventory/stock/", InventoryStockView.as_view(), name="inventory-stock"),
    path("inventory/ledger/", InventoryLedgerView.as_view(), name="inventory-ledger"),
    path("inventory/grns/", InventoryGRNsView.as_view(), name="inventory-grns"),
    path(
        "inventory/grns/<uuid:grn_id>/",
        InventoryGRNDetailView.as_view(),
        name="inventory-grn-detail",
    ),
    path("inventory/adjustments/", InventoryAdjustmentsView.as_view(), name="inventory-adjustments"),
    path(
        "inventory/adjustments/<uuid:adjustment_id>/",
        InventoryAdjustmentDetailView.as_view(),
        name="inventory-adjustment-detail",
    ),
    path(
        "inventory/material-issues/",
        InventoryMaterialIssuesView.as_view(),
        name="inventory-material-issues",
    ),
    path(
        "inventory/material-issues/<uuid:issue_id>/",
        InventoryMaterialIssueDetailView.as_view(),
        name="inventory-material-issue-detail",
    ),
    path("inventory/reorder-pr/", InventoryReorderPRView.as_view(), name="inventory-reorder-pr"),
    # Legacy stock endpoints (kept for stores / procurement)
    path("stock/", StockView.as_view(), name="stock"),
    path("stock/reorder-pr/", stock_reorder_pr, name="stock-reorder-pr"),
    path("stock/ledger/", stock_ledger_post, name="stock-ledger-post"),
    path(
        "stock/adjustments/<uuid:adjustment_id>/approve/",
        stock_adjustment_approve,
        name="stock-adjustment-approve",
    ),
    path(
        "stock/material-issues/<uuid:issue_id>/",
        material_issue_action,
        name="material-issue-action",
    ),
    path("stock-movements/", StockMovementsView.as_view(), name="stock-movements"),
    # Sales module (parties, territories, ASM/dealer/retail, returns, schemes)
    path("sales/overview/", SalesOverviewView.as_view(), name="sales-overview"),
    path("sales/options/", SalesOptionsView.as_view(), name="sales-options"),
    path("sales/parties/", SalesPartiesView.as_view(), name="sales-parties"),
    path("sales/parties/<uuid:party_id>/", SalesPartyDetailView.as_view(), name="sales-party-detail"),
    path("sales/territories/", SalesTerritoriesView.as_view(), name="sales-territories"),
    path(
        "sales/territories/<uuid:territory_id>/",
        SalesTerritoryDetailView.as_view(),
        name="sales-territory-detail",
    ),
    path("sales/asm-orders/", SalesASMOrdersView.as_view(), name="sales-asm-orders"),
    path(
        "sales/asm-orders/<uuid:order_id>/",
        SalesASMOrderDetailView.as_view(),
        name="sales-asm-order-detail",
    ),
    path("sales/dealer-orders/", SalesDealerOrdersView.as_view(), name="sales-dealer-orders"),
    path(
        "sales/dealer-orders/<uuid:order_id>/",
        SalesDealerOrderDetailView.as_view(),
        name="sales-dealer-order-detail",
    ),
    path("sales/retail-orders/", SalesRetailOrdersView.as_view(), name="sales-retail-orders"),
    path(
        "sales/retail-orders/<uuid:order_id>/",
        SalesRetailOrderDetailView.as_view(),
        name="sales-retail-order-detail",
    ),
    path("sales/returns/", SalesReturnsView.as_view(), name="sales-returns"),
    path(
        "sales/returns/<uuid:return_id>/",
        SalesReturnDetailView.as_view(),
        name="sales-return-detail",
    ),
    path("sales/schemes/", SalesSchemesView.as_view(), name="sales-schemes"),
    path(
        "sales/schemes/<uuid:scheme_id>/",
        SalesSchemeDetailView.as_view(),
        name="sales-scheme-detail",
    ),
    # Legacy finance SO list endpoints (kept for older clients)
    path("sales-orders/", SalesOrdersView.as_view(), name="sales-orders"),
    path("sales-orders/<uuid:so_id>/", sales_order_action, name="sales-order-action"),
    path("sales-by-region/", SalesByRegionView.as_view(), name="sales-by-region"),
    path("finance/", FinanceView.as_view(), name="finance"),
    path("finance/overview/", FinanceOverviewView.as_view(), name="finance-overview"),
    path("finance/options/", FinanceOptionsView.as_view(), name="finance-options"),
    path("finance/coa/", FinanceCOAView.as_view(), name="finance-coa"),
    path("finance/coa/<uuid:account_id>/", FinanceCOADetailView.as_view(), name="finance-coa-detail"),
    path("finance/vouchers/", FinanceVouchersView.as_view(), name="finance-vouchers"),
    path(
        "finance/vouchers/<uuid:voucher_id>/",
        FinanceVoucherDetailView.as_view(),
        name="finance-voucher-detail",
    ),
    # Legacy FBV post/reverse — prefer FinanceVoucherDetailView POST action
    path(
        "finance/vouchers/<uuid:voucher_id>/action/",
        finance_voucher_action,
        name="finance-voucher-action",
    ),
    path("finance/cash-banks/", FinanceCashBanksView.as_view(), name="finance-cash-banks"),
    path(
        "finance/cash-banks/<uuid:account_id>/",
        FinanceCashBankDetailView.as_view(),
        name="finance-cash-bank-detail",
    ),
    path("finance/day-book/", FinanceDayBookView.as_view(), name="finance-day-book"),
    path("finance/ledger/", FinanceLedgerView.as_view(), name="finance-ledger"),
    path("finance/purchases/", FinancePurchasesView.as_view(), name="finance-purchases"),
    path(
        "finance/purchases/<uuid:purchase_id>/",
        FinancePurchaseDetailView.as_view(),
        name="finance-purchase-detail",
    ),
    path("finance/purchase-orders/", FinancePurchaseOrdersView.as_view(), name="finance-purchase-orders"),
    path(
        "finance/purchase-orders/<uuid:po_id>/",
        FinancePurchaseOrderDetailView.as_view(),
        name="finance-purchase-order-detail",
    ),
    path("finance/sales/", FinanceSalesView.as_view(), name="finance-sales"),
    path(
        "finance/sales/<uuid:sales_id>/",
        FinanceSalesDetailView.as_view(),
        name="finance-sales-detail",
    ),
    path("finance/sales-orders/", FinanceSalesOrdersView.as_view(), name="finance-sales-orders"),
    path(
        "finance/sales-orders/<uuid:so_id>/",
        FinanceSalesOrderDetailView.as_view(),
        name="finance-sales-order-detail",
    ),
    path("finance/payments/", FinancePaymentsView.as_view(), name="finance-payments"),
    path(
        "finance/payments/action/",
        finance_payment_action,
        name="finance-payment-action",
    ),
    path("finance/receipts/", FinanceReceiptsView.as_view(), name="finance-receipts"),
    path("finance/debit-notes/", FinanceDebitNotesView.as_view(), name="finance-debit-notes"),
    path(
        "finance/debit-notes/<uuid:note_id>/",
        FinanceDebitNoteDetailView.as_view(),
        name="finance-debit-note-detail",
    ),
    path("finance/credit-notes/", FinanceCreditNotesView.as_view(), name="finance-credit-notes"),
    path(
        "finance/credit-notes/<uuid:note_id>/",
        FinanceCreditNoteDetailView.as_view(),
        name="finance-credit-note-detail",
    ),
    path("finance/income-expenses/", FinanceIncomeExpensesView.as_view(), name="finance-income-expenses"),
    path(
        "finance/income-expenses/<uuid:entry_id>/",
        FinanceIncomeExpenseDetailView.as_view(),
        name="finance-income-expense-detail",
    ),
    path("finance/pnl/", FinancePnLView.as_view(), name="finance-pnl"),
    path("finance/tax/", FinanceTaxView.as_view(), name="finance-tax"),
    path("finance/tax/<uuid:record_id>/", FinanceTaxDetailView.as_view(), name="finance-tax-detail"),
    path("finance/cheques/", FinanceChequesView.as_view(), name="finance-cheques"),
    path(
        "finance/cheques/<uuid:cheque_id>/",
        FinanceChequeDetailView.as_view(),
        name="finance-cheque-detail",
    ),
    path("procurement/", ProcurementView.as_view(), name="procurement"),
    path("procurement/overview/", ProcurementOverviewView.as_view(), name="procurement-overview"),
    path("procurement/options/", ProcurementOptionsView.as_view(), name="procurement-options"),
    path("procurement/vendors/", ProcurementVendorsView.as_view(), name="procurement-vendors"),
    path(
        "procurement/vendors/<uuid:vendor_id>/",
        ProcurementVendorDetailView.as_view(),
        name="procurement-vendor-detail",
    ),
    path(
        "procurement/requisitions/",
        ProcurementRequisitionsView.as_view(),
        name="procurement-requisitions",
    ),
    path(
        "procurement/requisitions/<uuid:pr_id>/",
        ProcurementRequisitionDetailView.as_view(),
        name="procurement-pr-detail",
    ),
    path("procurement/rfqs/", ProcurementRFQsView.as_view(), name="procurement-rfqs"),
    path(
        "procurement/rfqs/<uuid:rfq_id>/",
        ProcurementRFQDetailView.as_view(),
        name="procurement-rfq-detail",
    ),
    path("procurement/orders/", ProcurementOrdersView.as_view(), name="procurement-orders"),
    path(
        "procurement/orders/<uuid:po_id>/",
        ProcurementOrderDetailView.as_view(),
        name="procurement-po-detail",
    ),
    path("procurement/grns/", ProcurementGRNsView.as_view(), name="procurement-grns"),
    path(
        "procurement/grns/<uuid:grn_id>/",
        ProcurementGRNDetailView.as_view(),
        name="procurement-grn-detail",
    ),
    path("quality/", QualityView.as_view(), name="quality"),
    path("quality/overview/", QualityOverviewView.as_view(), name="quality-overview"),
    path("quality/options/", QualityOptionsView.as_view(), name="quality-options"),
    path("quality/incoming/", QualityIncomingView.as_view(), name="quality-incoming"),
    path(
        "quality/incoming/<uuid:inspection_id>/",
        QualityIncomingDetailView.as_view(),
        name="quality-incoming-detail",
    ),
    path("quality/ipqc/", QualityIPQCView.as_view(), name="quality-ipqc"),
    path(
        "quality/ipqc/<uuid:qc_id>/",
        QualityIPQCDetailView.as_view(),
        name="quality-ipqc-detail",
    ),
    path("quality/releases/", QualityReleaseView.as_view(), name="quality-releases"),
    path(
        "quality/releases/<uuid:release_id>/",
        QualityReleaseDetailView.as_view(),
        name="quality-release-detail",
    ),
    path("quality/lab/", QualityLabView.as_view(), name="quality-lab"),
    path(
        "quality/lab/<uuid:report_id>/",
        QualityLabDetailView.as_view(),
        name="quality-lab-detail",
    ),
    path("quality/ncrs/", QualityNCRView.as_view(), name="quality-ncrs"),
    path(
        "quality/ncrs/<uuid:ncr_id>/",
        QualityNCRDetailView.as_view(),
        name="quality-ncr-detail",
    ),
    path("quality/capas/", QualityCAPAView.as_view(), name="quality-capas"),
    path(
        "quality/capas/<uuid:capa_id>/",
        QualityCAPADetailView.as_view(),
        name="quality-capa-detail",
    ),
    path("quality/masters/", QualityMasterView.as_view(), name="quality-masters"),
    path(
        "quality/masters/<uuid:master_id>/",
        QualityMasterDetailView.as_view(),
        name="quality-master-detail",
    ),
    path("quality/qc/<uuid:qc_id>/", quality_qc_action, name="quality-qc-action"),
    path(
        "quality/releases/<uuid:release_id>/action/",
        quality_release_action,
        name="quality-release-action",
    ),
    path(
        "quality/incoming/<uuid:inspection_id>/action/",
        quality_incoming_action,
        name="quality-incoming-action",
    ),
    path("quality/ncr/", quality_ncr_create, name="quality-ncr-create"),
    path("quality/capa/<uuid:capa_id>/close/", quality_capa_close, name="quality-capa-close"),
    path("crm/", CrmView.as_view(), name="crm"),
    path("crm/overview/", CrmOverviewView.as_view(), name="crm-overview"),
    path("crm/options/", CrmOptionsView.as_view(), name="crm-options"),
    path("crm/deals/", CrmDealsView.as_view(), name="crm-deals"),
    path(
        "crm/deals/<uuid:deal_id>/detail/",
        CrmDealDetailView.as_view(),
        name="crm-deal-detail",
    ),
    path("crm/deals/<uuid:deal_id>/", crm_deal_action, name="crm-deal-action"),
    path("crm/complaints/", CrmComplaintsView.as_view(), name="crm-complaints"),
    path(
        "crm/complaints/<uuid:complaint_id>/",
        CrmComplaintDetailView.as_view(),
        name="crm-complaint-detail",
    ),
    path("crm/activities/", CrmActivitiesView.as_view(), name="crm-activities"),
    path(
        "crm/activities/<uuid:activity_id>/",
        CrmActivityDetailView.as_view(),
        name="crm-activity-detail",
    ),
    path("maintenance/", MaintenanceView.as_view(), name="maintenance"),
    path("maintenance/overview/", MaintenanceOverviewView.as_view(), name="maintenance-overview"),
    path("maintenance/options/", MaintenanceOptionsView.as_view(), name="maintenance-options"),
    path("maintenance/equipment/", MaintenanceEquipmentView.as_view(), name="maintenance-equipment"),
    path(
        "maintenance/equipment/<uuid:equipment_id>/",
        MaintenanceEquipmentDetailView.as_view(),
        name="maintenance-equipment-detail",
    ),
    path(
        "maintenance/work-orders/",
        MaintenanceWorkOrdersView.as_view(),
        name="maintenance-work-orders",
    ),
    path(
        "maintenance/work-orders/<uuid:wo_id>/",
        maintenance_wo_action,
        name="maintenance-wo-action",
    ),
    path(
        "maintenance/work-orders/<uuid:wo_id>/detail/",
        MaintenanceWorkOrderDetailView.as_view(),
        name="maintenance-work-order-detail",
    ),
    path(
        "maintenance/pm-schedules/",
        MaintenancePMSchedulesView.as_view(),
        name="maintenance-pm-schedules",
    ),
    path(
        "maintenance/pm-schedules/<uuid:schedule_id>/",
        MaintenancePMScheduleDetailView.as_view(),
        name="maintenance-pm-schedule-detail",
    ),
    path("maintenance/pm/generate/", maintenance_pm_generate, name="maintenance-pm-generate"),
    path(
        "maintenance/calibrations/",
        MaintenanceCalibrationsView.as_view(),
        name="maintenance-calibrations",
    ),
    path(
        "maintenance/calibrations/<uuid:calibration_id>/",
        MaintenanceCalibrationDetailView.as_view(),
        name="maintenance-calibration-detail",
    ),
    path("logistics/", LogisticsView.as_view(), name="logistics"),
    path("logistics/overview/", LogisticsOverviewView.as_view(), name="logistics-overview"),
    path("logistics/options/", LogisticsOptionsView.as_view(), name="logistics-options"),
    path("logistics/vehicles/", LogisticsVehiclesView.as_view(), name="logistics-vehicles"),
    path(
        "logistics/vehicles/<uuid:vehicle_id>/",
        LogisticsVehicleDetailView.as_view(),
        name="logistics-vehicle-detail",
    ),
    path("logistics/routes/", LogisticsRoutesView.as_view(), name="logistics-routes"),
    path(
        "logistics/routes/<uuid:route_id>/",
        LogisticsRouteDetailView.as_view(),
        name="logistics-route-detail",
    ),
    path("logistics/dispatches/list/", LogisticsDispatchesView.as_view(), name="logistics-dispatches-list"),
    path(
        "logistics/dispatches/<uuid:dispatch_id>/detail/",
        LogisticsDispatchDetailView.as_view(),
        name="logistics-dispatch-detail",
    ),
    path("logistics/dispatches/", logistics_dispatch_action, name="logistics-dispatch-create"),
    path(
        "logistics/dispatches/<uuid:dispatch_id>/",
        logistics_dispatch_action,
        name="logistics-dispatch-action",
    ),
    path("logistics/pods/", LogisticsPodsView.as_view(), name="logistics-pods"),
    path(
        "logistics/pods/<uuid:pod_id>/",
        LogisticsPodDetailView.as_view(),
        name="logistics-pod-detail",
    ),
    path("notifications/", NotificationsView.as_view(), name="notifications"),
    path(
        "notifications/read-all/",
        notification_mark_read,
        name="notifications-read-all",
    ),
    path(
        "notifications/<uuid:notification_id>/read/",
        notification_mark_read,
        name="notification-mark-read",
    ),
    path("commerce/", CommerceView.as_view(), name="commerce"),
    path("commerce/overview/", CommerceOverviewView.as_view(), name="commerce-overview"),
    path("commerce/options/", CommerceOptionsView.as_view(), name="commerce-options"),
    path("commerce/products/", CommerceProductsView.as_view(), name="commerce-products"),
    path(
        "commerce/products/<uuid:product_id>/",
        CommerceProductDetailView.as_view(),
        name="commerce-product-detail",
    ),
    path("commerce/orders/", CommerceOrdersView.as_view(), name="commerce-orders"),
    path(
        "commerce/orders/<uuid:order_id>/",
        CommerceOrderDetailView.as_view(),
        name="commerce-order-detail",
    ),
    path("commerce/categories/", CommerceCategoriesView.as_view(), name="commerce-categories"),
    path(
        "commerce/categories/<uuid:category_id>/",
        CommerceCategoryDetailView.as_view(),
        name="commerce-category-detail",
    ),
    path("feed/", FeedView.as_view(), name="feed"),
    path("feed/publish/", feed_publish, name="feed-publish"),
    path("feed/<uuid:post_id>/engage/", feed_engage, name="feed-engage"),
    path("chat/", ChatView.as_view(), name="chat"),
    path("chat/<uuid:thread_id>/messages/", chat_messages, name="chat-messages"),
    path("admin-console/", AdminView.as_view(), name="admin-console"),
    # Process — function-based dashboard + unified action (dynamic.md priority #1)
    path("process/", process_dashboard, name="process"),
    path("process/action/", process_action, name="process-action"),
    path(
        "process/runs/stages/<uuid:stage_id>/",
        process_run_stage_action,
        name="process-run-stage-action",
    ),
    path("media/", MediaView.as_view(), name="media"),
    path("media/overview/", MediaOverviewView.as_view(), name="media-overview"),
    path("media/options/", MediaOptionsView.as_view(), name="media-options"),
    path("media/assets/", MediaAssetsView.as_view(), name="media-assets"),
    path(
        "media/assets/<uuid:asset_id>/",
        MediaAssetDetailView.as_view(),
        name="media-asset-detail",
    ),
    path("media/live/", MediaLiveStreamsView.as_view(), name="media-live"),
    path(
        "media/live/<uuid:stream_id>/",
        MediaLiveStreamDetailView.as_view(),
        name="media-live-detail",
    ),
    path("media/playlists/", MediaPlaylistsView.as_view(), name="media-playlists"),
    path(
        "media/playlists/<uuid:playlist_id>/",
        MediaPlaylistDetailView.as_view(),
        name="media-playlist-detail",
    ),
    path("payments/", PaymentsView.as_view(), name="payments"),
    path("payments/overview/", PaymentsOverviewView.as_view(), name="payments-overview"),
    path("payments/options/", PaymentsOptionsView.as_view(), name="payments-options"),
    path("payments/gateways/", PaymentsGatewaysView.as_view(), name="payments-gateways"),
    path(
        "payments/transactions/",
        PaymentsTransactionsView.as_view(),
        name="payments-transactions",
    ),
    path(
        "payments/transactions/<uuid:txn_id>/",
        PaymentsTransactionDetailView.as_view(),
        name="payments-transaction-detail",
    ),
    path("payments/campaigns/", PaymentsCampaignsView.as_view(), name="payments-campaigns"),
    path(
        "payments/campaigns/<uuid:campaign_id>/",
        PaymentsCampaignDetailView.as_view(),
        name="payments-campaign-detail",
    ),
    path("governance/", GovernanceView.as_view(), name="governance"),
    path("audit/", AuditView.as_view(), name="audit"),
    path("auth-kyc/", AuthKycView.as_view(), name="auth-kyc"),
    path("auth-kyc/<uuid:kyc_id>/verify/", auth_kyc_verify, name="auth-kyc-verify"),
    path("it/", ItView.as_view(), name="it"),
    path("it/overview/", ItOverviewView.as_view(), name="it-overview"),
    path("it/options/", ItOptionsView.as_view(), name="it-options"),
    path("it/tickets/", ItTicketsView.as_view(), name="it-tickets"),
    path("it/tickets/<uuid:ticket_id>/", ItTicketDetailView.as_view(), name="it-ticket-detail"),
    path("it/sessions/", ItSessionsView.as_view(), name="it-sessions"),
    path("docs/", DocsView.as_view(), name="docs"),
    path("docs/overview/", DocsOverviewView.as_view(), name="docs-overview"),
    path("docs/options/", DocsOptionsView.as_view(), name="docs-options"),
    path("docs/documents/", DocsDocumentsView.as_view(), name="docs-documents"),
    path(
        "docs/documents/<uuid:doc_id>/",
        DocsDocumentDetailView.as_view(),
        name="docs-document-detail",
    ),
    path("docs/templates/", DocsTemplatesView.as_view(), name="docs-templates"),
    path(
        "docs/templates/<uuid:template_id>/",
        DocsTemplateDetailView.as_view(),
        name="docs-template-detail",
    ),
    path("customer/", CustomerView.as_view(), name="customer"),
    path("customer/overview/", CustomerOverviewView.as_view(), name="customer-overview"),
    path("customer/options/", CustomerOptionsView.as_view(), name="customer-options"),
    path("customer/orders/", CustomerOrdersView.as_view(), name="customer-orders"),
    path(
        "customer/orders/<uuid:order_id>/",
        CustomerOrderDetailView.as_view(),
        name="customer-order-detail",
    ),
    path("customer/addresses/", CustomerAddressesView.as_view(), name="customer-addresses"),
    path(
        "customer/addresses/<uuid:address_id>/",
        CustomerAddressDetailView.as_view(),
        name="customer-address-detail",
    ),
    path("customer/nearest/", CustomerNearestShopsView.as_view(), name="customer-nearest"),
    path("rnd/", RndView.as_view(), name="rnd"),
    path("rnd/overview/", RndOverviewView.as_view(), name="rnd-overview"),
    path("rnd/options/", RndOptionsView.as_view(), name="rnd-options"),
]
