/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as RndRouteImport } from './routes/rnd'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ItRouteImport } from './routes/it'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HrRouteImport } from './routes/hr'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CommerceRouteImport } from './routes/commerce'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthKycRouteImport } from './routes/auth-kyc'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminRolesRouteImport } from './routes/super-admin.roles'
import { Route as SuperAdminCompaniesRouteImport } from './routes/super-admin.companies'
import { Route as RegisterCompanyRouteImport } from './routes/register.company'
import { Route as PortalPortalTypeRouteImport } from './routes/portal.$portalType'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const RndRoute = RndRouteImport.update({
  id: '/rnd',
  path: '/rnd',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceRoute = CommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthKycRoute = AuthKycRouteImport.update({
  id: '/auth-kyc',
  path: '/auth-kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminRolesRoute = SuperAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminCompaniesRoute = SuperAdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => SuperAdminRoute,
} as any)
const RegisterCompanyRoute = RegisterCompanyRouteImport.update({
  id: '/register/company',
  path: '/register/company',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalTypeRoute = PortalPortalTypeRouteImport.update({
  id: '/portal/$portalType',
  path: '/portal/$portalType',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/audit': typeof AuditRoute
  '/auth-kyc': typeof AuthKycRoute
  '/chat': typeof ChatRoute
  '/commerce': typeof CommerceRoute
  '/copilot': typeof CopilotRoute
  '/crm': typeof CrmRoute
  '/customer': typeof CustomerRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/it': typeof ItRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/maintenance': typeof MaintenanceRoute
  '/media': typeof MediaRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/process': typeof ProcessRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/rnd': typeof RndRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/tasks': typeof TasksRoute
  '/portal/$portalType': typeof PortalPortalTypeRoute
  '/register/company': typeof RegisterCompanyRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/audit': typeof AuditRoute
  '/auth-kyc': typeof AuthKycRoute
  '/chat': typeof ChatRoute
  '/commerce': typeof CommerceRoute
  '/copilot': typeof CopilotRoute
  '/crm': typeof CrmRoute
  '/customer': typeof CustomerRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/it': typeof ItRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/maintenance': typeof MaintenanceRoute
  '/media': typeof MediaRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/process': typeof ProcessRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/rnd': typeof RndRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/tasks': typeof TasksRoute
  '/portal/$portalType': typeof PortalPortalTypeRoute
  '/register/company': typeof RegisterCompanyRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/audit': typeof AuditRoute
  '/auth-kyc': typeof AuthKycRoute
  '/chat': typeof ChatRoute
  '/commerce': typeof CommerceRoute
  '/copilot': typeof CopilotRoute
  '/crm': typeof CrmRoute
  '/customer': typeof CustomerRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/it': typeof ItRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/maintenance': typeof MaintenanceRoute
  '/media': typeof MediaRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/process': typeof ProcessRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/rnd': typeof RndRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/tasks': typeof TasksRoute
  '/portal/$portalType': typeof PortalPortalTypeRoute
  '/register/company': typeof RegisterCompanyRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apps'
    | '/audit'
    | '/auth-kyc'
    | '/chat'
    | '/commerce'
    | '/copilot'
    | '/crm'
    | '/customer'
    | '/docs'
    | '/feed'
    | '/finance'
    | '/governance'
    | '/hr'
    | '/inventory'
    | '/it'
    | '/jobs'
    | '/login'
    | '/logistics'
    | '/maintenance'
    | '/media'
    | '/notifications'
    | '/payments'
    | '/process'
    | '/procurement'
    | '/production'
    | '/quality'
    | '/rnd'
    | '/sales'
    | '/settings'
    | '/stores'
    | '/super-admin'
    | '/tasks'
    | '/portal/$portalType'
    | '/register/company'
    | '/super-admin/companies'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apps'
    | '/audit'
    | '/auth-kyc'
    | '/chat'
    | '/commerce'
    | '/copilot'
    | '/crm'
    | '/customer'
    | '/docs'
    | '/feed'
    | '/finance'
    | '/governance'
    | '/hr'
    | '/inventory'
    | '/it'
    | '/jobs'
    | '/login'
    | '/logistics'
    | '/maintenance'
    | '/media'
    | '/notifications'
    | '/payments'
    | '/process'
    | '/procurement'
    | '/production'
    | '/quality'
    | '/rnd'
    | '/sales'
    | '/settings'
    | '/stores'
    | '/tasks'
    | '/portal/$portalType'
    | '/register/company'
    | '/super-admin/companies'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apps'
    | '/audit'
    | '/auth-kyc'
    | '/chat'
    | '/commerce'
    | '/copilot'
    | '/crm'
    | '/customer'
    | '/docs'
    | '/feed'
    | '/finance'
    | '/governance'
    | '/hr'
    | '/inventory'
    | '/it'
    | '/jobs'
    | '/login'
    | '/logistics'
    | '/maintenance'
    | '/media'
    | '/notifications'
    | '/payments'
    | '/process'
    | '/procurement'
    | '/production'
    | '/quality'
    | '/rnd'
    | '/sales'
    | '/settings'
    | '/stores'
    | '/super-admin'
    | '/tasks'
    | '/portal/$portalType'
    | '/register/company'
    | '/super-admin/companies'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppsRoute: typeof AppsRoute
  AuditRoute: typeof AuditRoute
  AuthKycRoute: typeof AuthKycRoute
  ChatRoute: typeof ChatRoute
  CommerceRoute: typeof CommerceRoute
  CopilotRoute: typeof CopilotRoute
  CrmRoute: typeof CrmRoute
  CustomerRoute: typeof CustomerRoute
  DocsRoute: typeof DocsRoute
  FeedRoute: typeof FeedRoute
  FinanceRoute: typeof FinanceRoute
  GovernanceRoute: typeof GovernanceRoute
  HrRoute: typeof HrRoute
  InventoryRoute: typeof InventoryRoute
  ItRoute: typeof ItRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  LogisticsRoute: typeof LogisticsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MediaRoute: typeof MediaRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  ProcessRoute: typeof ProcessRoute
  ProcurementRoute: typeof ProcurementRoute
  ProductionRoute: typeof ProductionRoute
  QualityRoute: typeof QualityRoute
  RndRoute: typeof RndRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  StoresRoute: typeof StoresRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TasksRoute: typeof TasksRoute
  PortalPortalTypeRoute: typeof PortalPortalTypeRoute
  RegisterCompanyRoute: typeof RegisterCompanyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rnd': {
      id: '/rnd'
      path: '/rnd'
      fullPath: '/rnd'
      preLoaderRoute: typeof RndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce': {
      id: '/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof CommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-kyc': {
      id: '/auth-kyc'
      path: '/auth-kyc'
      fullPath: '/auth-kyc'
      preLoaderRoute: typeof AuthKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/roles': {
      id: '/super-admin/roles'
      path: '/roles'
      fullPath: '/super-admin/roles'
      preLoaderRoute: typeof SuperAdminRolesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/companies': {
      id: '/super-admin/companies'
      path: '/companies'
      fullPath: '/super-admin/companies'
      preLoaderRoute: typeof SuperAdminCompaniesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/register/company': {
      id: '/register/company'
      path: '/register/company'
      fullPath: '/register/company'
      preLoaderRoute: typeof RegisterCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$portalType': {
      id: '/portal/$portalType'
      path: '/portal/$portalType'
      fullPath: '/portal/$portalType'
      preLoaderRoute: typeof PortalPortalTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminCompaniesRoute: typeof SuperAdminCompaniesRoute
  SuperAdminRolesRoute: typeof SuperAdminRolesRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminCompaniesRoute: SuperAdminCompaniesRoute,
  SuperAdminRolesRoute: SuperAdminRolesRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppsRoute: AppsRoute,
  AuditRoute: AuditRoute,
  AuthKycRoute: AuthKycRoute,
  ChatRoute: ChatRoute,
  CommerceRoute: CommerceRoute,
  CopilotRoute: CopilotRoute,
  CrmRoute: CrmRoute,
  CustomerRoute: CustomerRoute,
  DocsRoute: DocsRoute,
  FeedRoute: FeedRoute,
  FinanceRoute: FinanceRoute,
  GovernanceRoute: GovernanceRoute,
  HrRoute: HrRoute,
  InventoryRoute: InventoryRoute,
  ItRoute: ItRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  LogisticsRoute: LogisticsRoute,
  MaintenanceRoute: MaintenanceRoute,
  MediaRoute: MediaRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  ProcessRoute: ProcessRoute,
  ProcurementRoute: ProcurementRoute,
  ProductionRoute: ProductionRoute,
  QualityRoute: QualityRoute,
  RndRoute: RndRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  StoresRoute: StoresRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TasksRoute: TasksRoute,
  PortalPortalTypeRoute: PortalPortalTypeRoute,
  RegisterCompanyRoute: RegisterCompanyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
